version: 0.0
os: linux

files:
  - source: /
    destination: /product
permissions:
  - object: /product/
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root